from .specialized_loss import (
    NamedTargetStopWordAwareMSE,
    NamedTargetStopWordAwareMAE,
    NamedTargetStopWordAwareKLeastSE,
    NamedTargetStopWordAwareKLeastSEEvalUpdate,
    NamedTargetStopWordAwareKLeastAE,
    NamedTargetStopWordAwareKLeastAEEvalUpdate,
    NamedTargetStopWordAwarePearsonDistance,
    NamedTargetStopWordAwareBinaryCrossEntropyWithLogits,
    NamedTargetStopWordAwareCrossEntropy,
    NamedTargetStopWordAwareSoftLabelCrossEntropy,
    NamedTargetSingleMSE,
    NamedTargetSingleMAE,
    NamedTargetSingleKLeastSE,
    NamedTargetSingleKLeastSEEvalUpdate,
    NamedTargetSingleKLeastAE,
    NamedTargetSingleKLeastAEEvalUpdate,
    NamedTargetSinglePearsonDistance,
    NamedTargetSingleBinaryCrossEntropyWithLogits,
    NamedTargetSingleCrossEntropy,
    NamedTargetSingleSoftLabelCrossEntropy)


__all__ = [
    'NamedTargetStopWordAwareMSE',
    'NamedTargetStopWordAwareMAE',
    'NamedTargetStopWordAwareKLeastSE',
    'NamedTargetStopWordAwareKLeastSEEvalUpdate',
    'NamedTargetStopWordAwareKLeastAE',
    'NamedTargetStopWordAwareKLeastAEEvalUpdate',
    'NamedTargetStopWordAwarePearsonDistance',
    'NamedTargetStopWordAwareBinaryCrossEntropyWithLogits',
    'NamedTargetStopWordAwareCrossEntropy',
    'NamedTargetStopWordAwareSoftLabelCrossEntropy',
    'NamedTargetSingleMSE',
    'NamedTargetSingleMAE',
    'NamedTargetSingleKLeastSE',
    'NamedTargetSingleKLeastSEEvalUpdate',
    'NamedTargetSingleKLeastAE',
    'NamedTargetSingleKLeastAEEvalUpdate',
    'NamedTargetSinglePearsonDistance',
    'NamedTargetSingleBinaryCrossEntropyWithLogits',
    'NamedTargetSingleCrossEntropy',
    'NamedTargetSingleSoftLabelCrossEntropy']
